name: Run Telegram Report Script

on:
  workflow_dispatch:   # run manually
  schedule:
    - cron: "0 6 * * 1"   # runs daily at 09:00 in +3 UTC every monday

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Chisinau

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run report script
        env:
          DB_LINK: ${{ secrets.DB_LINK }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python run.py
