name: Run Telegram Report Script

on:
  workflow_dispatch:   # run manually
  schedule:
    - cron: "0 9 * * *"   # runs daily at 09:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run report script
        env:
          DB_LINK: ${{ secrets.DB_LINK }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python run.py
